version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
  logic:
    build:
      context: .
      dockerfile: script/Dockerfile
    env_file:
      - .env
    restart: always
